### ISSUE TITLE
`LeaseManager::spawn` task terminates abruptly in the face of API errors

### ISSUE THREAD

**Issue by hawkw** [olix0r/kubert#134]
Currently, the task spawned by Kubert's `LeaseManager::spawn` will complete with an error if the call to `ensure_claimed` fails: https://github.com/olix0r/kubert/blob/3f954ab51bdcd7bb927151fe9621a8d7acac4ad9/kubert/src/lease.rs#L303

The `ensure_claimed` method calls `renew` (if the lease holder) or `acquire` (if not holding the lease), and returns an error if either of those methods returns an error that doesn't indicate a conflicti: https://github.com/olix0r/kubert/blob/3f954ab51bdcd7bb927151fe9621a8d7acac4ad9/kubert/src/lease.rs#L188-L197
https://github.com/olix0r/kubert/blob/3f954ab51bdcd7bb927151fe9621a8d7acac4ad9/kubert/src/lease.rs#L212-L221

This means that any error encountered by those methods will result in the `LeaseManager::spawn` background task terminating abruptly, closing the returned `watch` channel.

Perhaps the `LeaseManager` task should instead retry in the face of these errors, as it is generally intended to run in the background for a controller's entire lifetime?

**Comment by hawkw** [comment]
Wondering if we need any kind of real retry with backoff logic for the `ensure_claimed` call, or if it would be sufficient to just continue looping and try again...

**Comment by olix0r** [comment]
What classes of errors might we encounter? How should they each be handled?

**Comment by hawkw** [comment]
@olix0r I'm investigating the specific errors that were encountered by Linkerd (running with `kube`'s logging enabled); will report back.

**Comment by hawkw** [comment]
I believe this should have been closed by #148.
